export const p_remaining = document.querySelector('#remaining')
export const p_deck = document.querySelector('#deck')
export const p_winner = document.querySelector('#winner')
export const d_player = document.querySelector('#player')
export const d_bot = document.querySelector('#bot')
